version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting world.
          command: echo Hello funny world.

      - run:
          name: Print the Current Time
          command: date